### ISSUE TITLE
TODO for rel 0.3.0

### ISSUE THREAD

**Issue by themanyfaceddemon** [themanyfaceddemon/Barotrauma_Modding_Tool#35]
God save my soul

# Visual modding
- [ ] Working with sprites
- [ ] Working with adding new buildings
- [ ] Working with adding new weapons
- [ ] Working with adding new medicines
- [ ] Working with adding new tools
- [ ] Working with adding new grenades
- [ ] Working with adding new genes
- [ ] Working with adding new afflictions
